### ISSUE TITLE
Message about user directory permission error should be more user friendly.

### ISSUE THREAD

**Issue by tx1683** [yedino/galaxy42#386]

**Comment by rfreemobile** [comment]
This is worked on in PR #391 

(program should auto-switch to the HOME of user who called sudo; unless special option --home-env is set then always HOME is read if user wants to set special one by hand)

**Comment by rfree-d** [comment]
It's fixed now - we automatically switch to default home of the user who used  sudo .....

If that is not what you want, start program as    sudo HOME=/etc/something/ ./tunserver.elf --home-env

as explained nicelly in the documentation now :)

Please reopen if still any problem (or ping us)

👍
