### ISSUE TITLE
Possible data race in rpc server

### ISSUE THREAD

**Issue by mikurys** [yedino/galaxy42#428]
commit: 292dd1506d8e11c2f7766f1fd0c32e073fa48b47
c_rpc_server constructor run async_accept so we can get rpc messages from now.
In main thread after rpc_server creation, c_rpc_server::m_rpc_functions_map is modified by function c_rpc_server::add_rpc_function without locking it, so it is possible data race here if we get rpc message in the same time.

**Comment by robertoleksy** [comment]
fixed by #432
